### ISSUE TITLE
sinto installation - problem with python

### ISSUE THREAD

**Issue by mirifax** [timoast/sinto#26]
Hi, 
I installed sinto successfully with python2 etc. But I seem to have an error with python: 

File "/home/mfaxel/lib/python2.7/site-packages/sinto-0.7.2.2-py2.7.egg/sinto/tagtorg.py", line 9
    return "\t".join(f"{k}:{v}" for k, v in line.items())
                              ^
SyntaxError: invalid syntax

Is there a workaround or anyone already had this problem? 
Thanks in advance!

**Comment by timoast** [comment]
Sinto requires python 3

**Comment by binggan007** [comment]
Hi I have similar problem. My command sinto fragments XX.bam:

Traceback (most recent call last):
  File "/home/fuy3/.local/bin/sinto", line 5, in <module>
    from sinto.arguments import main
  File "/home/fuy3/.local/lib/python3.5/site-packages/sinto/arguments.py", line 4, in <module>
    from sinto import cli
  File "/home/fuy3/.local/lib/python3.5/site-packages/sinto/cli.py", line 1, in <module>
    from sinto import (
  File "/home/fuy3/.local/lib/python3.5/site-packages/sinto/tagtorg.py", line 9
    return "\t".join(f"{k}:{v}" for k, v in line.items())
                              ^
SyntaxError: invalid syntax

Thank you!
