### ISSUE TITLE
Error with addtags on a transcriptome-aligned BAM file

### ISSUE THREAD

**Issue by austin-abbvie** [timoast/sinto#30]
Hi! I love your tool and I've been using it quite extensively. I have found an error with `sinto addtags` on a transcriptome-aligned BAM file. I believe the nature of the error is that it treats every transcript as a chromosome, and there are many thousands compared to a 'normal' amount of chromosomes. Is there a better way to handle breaking chromosomes without recursion?

```
sinto addtags -b Enrichment_PCR_A1-1A_t.bam -m readname -o Enrichment_PCR_A1-1A_t.tagged.bam -p 88 -f sinto_tagfile.txt
Function run_addtags called with the following arguments:

bam     Enrichment_PCR_A1-1A_t.bam
tagfile sinto_tagfile.txt
output  Enrichment_PCR_A1-1A_t.tagged.bam
trim_suffix     False
sam     False
nproc   88
mode    readname
func    <function run_addtags at 0x7f4837808d30>
Traceback (most recent call last):
  File ".../lib/python3.9/site-packages/sinto/utils.py", line 75, in find_chromosome_break
    return find_chromosome_break(position, chromosomes, current_chrom + 1)
  File ".../lib/python3.9/site-packages/sinto/utils.py", line 75, in find_chromosome_break
    return find_chromosome_break(position, chromosomes, current_chrom + 1)
  File ".../lib/python3.9/site-packages/sinto/utils.py", line 75, in find_chromosome_break
    return find_chromosome_break(position, chromosomes, current_chrom + 1)
  [Previous line repeated 996 more times]
  File ".../lib/python3.9/site-packages/sinto/utils.py", line 71, in find_chromosome_break
    if position <= chromosomes[current_chrom]:
RecursionError: maximum recursion depth exceeded in comparison
```
Attempting to run with 1 processor resulted in the same error. 
bam file:
```
d3ce747b-2355-4385-9d2e-5d1f308a5e8b	256	MSTRG.1.1	1	0	64S85M1I10M1D46M3D78M1I83M2D4M3D30M3D12M613N22M1I144M11D5M3I20M1I29M3D62M1D4M2D3M1D111M1D13M1I23M63S	*	0	0	*	*	NM:i:65	ms:i:513	AS:i:489	nn:i:0	ts:A:+	tp:A:S	cm:i:124	s1:i:589	de:f:0.0537	MD:Z:41C37C1G13^T18A1G0A24^CCA0C41A0C9G24G3G2G75^CG4^GAG30^CAC113G4T33T25^ACCCCCCAACA7G19A26^GGG2A13G12C8A23^A4^CG3^C16G52T19A21^C6A29	rl:i:0
4909bb1f-6734-4e67-86e2-2f6dce0feff9	0	MSTRG.1.1	1	0	65S100M1D44M1D63M1D9M5D11M1D45M2I42M1I27M1I4M2D12M1D11M1D30M2D11M5D25M1D1M3I11M2D53M64S	*	0	0	TATTGTACTTCGTTCAGTTACGTATTGCTGGGGAAGCAGTGGTACAACGCAGGTACATGGGGCCTCCGGAAGTGCGGATCCCAGCGGCAGTCGTGTAGCTGAGCAGGCCTGGGGCTTGGTTCTATGTCCCTGTGGCTATGTTTCCAGTGTCCTCTGGGTGTTTCCAGAGCAACAAGAAACGAATAAATCTCTGCCCCGCAGCGCCTCCACCCAGAGACCCGGACCAAATTCACACAGGACAATCTGTGCCGTGCCCAGCGCAAGCGCCTGGATCGGCCAACGGACCTTGTGGTTCCATCCTTCGCGACACCTCCGAGGACCTGGGACTCCAGTGTGAAGCGCCGTGAACCTGGCCTTCGGGCGCCGCTGTGAGGAACTGGAGGGACGCGCGGCACAAGCTGCAGCACCACCCTGCAAGGTGGGGCACCTGAACCCCGAGACGGCTCCGGCGCCTGCCCACCACTCTGCCCTCTCATCACCTGGGCCCTCAACCCTTTTCTCCTTATATTCCCACTTGTCGAGGGACCCCAGAAGCAAGTGTCACCTCTCCATAAACCTATGTAAAACCAGGCAAAAAAAAAAAAAAAAAAAAACATTTGTAGATCTTCACGGAGCGGAAGAGATCGGAAAGAGCA	$#%'07:8==<?CA@=?AB?7;<===%2432))/.%%%;=;31-*+*../.)775=@?B@@A==@::?=:;6??46:=<4454.11'$$%4*150,,&--0.$%%,9:;9;=;74578:<<;:3128?>578880-'-%(4><+<469:>:4<::76.4/::<823'9;;<57871A=;11142:79:878859865,//,.+/...3*+-*+.333955.460/0+(24499955;?=>?>@:<;8=1379@@@>;:/.00287854221/&)')10.&#$('%$$%'*'''-((1>=9:?D;67<;B>?A<;>=99;9:;@ABE@:BB9;7/(+)&*45999-,6:5;=::?>>>896:77=>)%%7&>@8>DCEC388/29</3=@@C@==CFC5><522-*+3379:44-,+'056&-212277697400/.&',2448<=>969609861-.,)-046;:61/0132)6332.-+(')).2-+/+-%*&+6<>;<:0'(&&'&)56==8<7'/145.1>?<<>DFAE728<9>?@=<?>>?2><>AAIF?;>DB?B?ABEB;=<<B=?BG@B@D@A@C??<=7978;/59898,445:66<=96356<?8:>G;7/58>949;<1.0,'&	NM:i:46	ms:i:293	AS:i:293	nn:i:0	ts:A:+	tp:A:P	cm:i:68	s1:i:350	s2:i:350	de:f:0.0621	MD:Z:23G17C58^A44^C18G22A0C9G10^C9^CTGTG2T0G2G4^A0C1G115^CA12^C11^A30^CC11^CCTGG14A1C8^C1G8A1^CC32G20	rl:i:25
35e30db5-064c-4fb7-b116-81d590761199	256	MSTRG.1.1	1	0	76S26M1I22M4I2M2D2M1I6M1I35M1D22M2D6M3D16M2D9M7D6M6I87M1D26M1D91M1D8M3I21M1D38M1D31M1D40M63S	*	0	0	*	*	NM:i:74	ms:i:172	AS:i:172	nn:i:0	ts:A:+	tp:A:S	cm:i:42	s1:i:255	de:f:0.1035	MD:Z:23G17C8^TT8G5G28^T15G2A3^AT0A5^CTG2C1G11^CC9^CGGACCA7A16A0C9G25G2G2G18G0A1A0C2^C26^C20G0C0C27A0C0A3T0G2G19G10^C15G13^A24C0T2G9^C31^C24G15	rl:i:0
27cb0203-4357-4c90-a809-0a29640741b6	256	MSTRG.1.1	1	0	67S132M2I68M2D79M3D80M250S	*	0	0	*	*	NM:i:15	ms:i:294	AS:i:294	nn:i:0	ts:A:+	tp:A:S	cm:i:86	s1:i:322	de:f:0.0304	MD:Z:41C91G53A0C9G1^GC25G2G50^CGC1G78	rl:i:0
260f47db-336a-49ab-9fb3-93310a1377a1	256	MSTRG.1.1	1	0	62S64M2I37M5D9M4I16M1I2M3D9M3D23M1I11M1D15M1D10M1I3M1I3M2I22M1D27M1D34M1D8M5D65M2D14M5D10M1D33M1D25M2D4M1D32M95S	*	0	0	*	*	NM:i:74	ms:i:154	AS:i:154	nn:i:0	ts:A:+	tp:A:S	cm:i:58	s1:i:273	de:f:0.1024	MD:Z:41C22C1G34^AGAGC5G3C17^GCA7C1^CCC34^G4A0C4A0G0C0G1^G3G21G2G2G6^T0G10G7C2G0G3^T0G33^G0G7^TGTGA65^GA14^CCTGC6C0T2^G0C2C12G16^C25^GA4^C24G7	rl:i:22
462e1896-1f91-42b5-901c-db9f4fb92c16	256	MSTRG.1.1	1	0	97S90M1D51M1D28M1I2M2I78M3I7M1I17M2D83M613N100M5D62M1I16M3I8M1D7M2I5M1D28M2D48M2I2M1D6M3D8M1I5M3I43M1D70M82S	*	0	0	*	*	NM:i:59	ms:i:497	AS:i:473	nn:i:0	ts:A:+	tp:A:S	cm:i:166	s1:i:629	de:f:0.0536	MD:Z:90^G51^C16A0C1A89A5G16^GT27G152T0G1^AGCTG0C3C0A73G6^A4G0G6^A28^GA50^T3C2^GGA13G42^C6T0A10C0A1C0A47	rl:i:0
```
tagfile

```
d129905b-f46c-4287-be0b-78bcfbc33d41    CB      ATCTTGACCTGCAACG
0b337571-132f-4f0a-b4dd-b5df16d9654b    CB      ACGTTATTGGTCACTC
4fa9ab30-90ea-4041-a30a-18368e288a08    CB      CAACGTGGTGGAGTCT
b6105613-6ccb-466b-9896-12bba3f9b999    CB      AGCGACCAACGATATT
77ee2019-2acd-4cc9-8345-51f88617466d    CB      GTTACCTACAACTTGC
```

Thank you! In the meantime, I may hack together some bash script to operate on the sam file.

**Comment by timoast** [comment]
You can try setting the recursion limit higher by editing here: https://github.com/timoast/sinto/blob/master/sinto/arguments.py#L345

Let me know if that fixes it, if so I can adjust the recursion limit higher in the codebase

**Comment by austin-abbvie** [comment]
Setting it to 150,000 resulted in `Segmentation fault (core dumped)` without exceeding available RAM.

**Comment by timoast** [comment]
That's weird...did you clone the repo, make the edit, and then run `python setup.py install`?

**Comment by austin-abbvie** [comment]
Following those instructions, I still was unable to make it run with a recursion depth of 150,000. Still a segment fault with ~22Gb/384 of RAM. Trying with 500,000 resulted in the exact same behavior, stalling out at that RAM usage and dumping about a minute later.

**Comment by timoast** [comment]
Not really sure what the issue is but I increased the recursion limit, can you try reinstalling from github and see if it's fixed?
