### ISSUE TITLE
error filterbarcodes with 10x ATAC bam

### ISSUE THREAD

**Issue by LiNk-NY** [timoast/sinto#45]
Hi Tim, @timoast 

Thanks for helping me get the `--cells` input figured out.
I've tested this with 10 barcodes and the function mentioned in #44 works well with this format. 

Now, running the full `filterbarcodes` command, I get an error that I cannot understand. 
I am using the ATAC data from 10X. 

This is my script:

```sh
export sinto=$HOME/.local/bin/sinto
export BAM_FILE="$HOME/data/10x/pbmc_3k/pbmc_granulocyte_sorted_3k_atac_possorted_bam.bam"
export TEST_BCODES="$HOME/data/10x/pbmc_3k/test_atac_barcodes.tsv"

cd ~/data/10x/pbmc_3k/sinto_filterbarcodes

$sinto filterbarcodes \
    --bam $BAM_FILE \
    --cells $TEST_BCODES \
    --nproc 10 \
    --barcodetag "CB"
```

My barcodes `.tsv` file: 

```sh
mramos@supermicro ~/data/10x/pbmc_3k/sinto_filterbarcodes $ cat $TEST_BCODES | head -3
"TTAGTCAGTCCTCCCA-1"    "A"
"CATATAGAGTCAAGAC-1"    "B"
"GATATGATCTAATCCG-1"    "C"
```

The output of the command: 

```
Function run_filterbarcodes called with the following arguments:

bam     ./data/10x/pbmc_3k/pbmc_granulocyte_sorted_3k_atac_possorted_bam.bam
cells   ./data/10x/pbmc_3k/test_atac_barcodes.tsv
trim_suffix     False
nproc   10
barcode_regex   None
barcodetag      CB
func    <function run_filterbarcodes at 0x7fdd4fb03670>
[E::hts_open_format] Failed to open file "TTAGTCAGTCCTCCCA-1_L99RMI" : No such file or directory
samtools merge: fail to open "TTAGTCAGTCCTCCCA-1_L99RMI": No such file or directory
[E::hts_open_format] Failed to open file "TTAGTCAGTCCTCCCA-1.tmp" : No such file or directory
samtools reheader: fail to open file 'TTAGTCAGTCCTCCCA-1.tmp': No such file or directory
Traceback (most recent call last):
  File "/.local/bin/sinto", line 8, in <module>
    sys.exit(main())
  File "/.local/lib/python3.8/site-packages/sinto/arguments.py", line 457, in main
    options.func(options)
  File "/.local/lib/python3.8/site-packages/sinto/utils.py", line 23, in wrapper
    func(args)
  File "/.local/lib/python3.8/site-packages/sinto/cli.py", line 17, in run_filterbarcodes
    filterbarcodes.filterbarcodes(
  File "/.local/lib/python3.8/site-packages/sinto/filterbarcodes.py", line 119, in filterbarcodes
    mergeAll(idents=idents, classes=unique_classes, nproc=nproc, header = headerfile, remove=True)
  File "/.local/lib/python3.8/site-packages/sinto/filterbarcodes.py", line 58, in mergeAll
    raise Exception("samtools merge failed, temp files not deleted")
Exception: samtools merge failed, temp files not deleted
```

Thank you for taking a look!

Best regards,
Marcel

**Comment by timoast** [comment]
It could be the quotation marks causing a problem, can you try saving the barcode file without quotes and try again?

**Comment by LiNk-NY** [comment]
That helped. Thank you.
