### ISSUE TITLE
sinto filterbarcodes Remote I/O error

### ISSUE THREAD

**Issue by 23Niklas** [timoast/sinto#58]
Hi Tim, 

I want to use the sinto filterbarcodes function from your package to generate separate BAM files for each barcode. Unfortunately I'm getting an error which I think results from filterbarcodes wanting to extract reads from BAM files that are already extracted. But maybe you have a better explanation of the error below. The BAM file I'm using has an index bai file in the same folder and the barcodes.txt file has two identical columns with 5207 rows and is tab-delimited. The format is: 
ACTACGACACTTACAG-1   ACTACGACACTTACAG-1
...

Thanks a lot for your help, I appreciate it!

Function run_filterbarcodes called with the following arguments:

bam     /path/bamfile.bam
cells   /path/barcodes.txt
trim_suffix     False
nproc   64
barcode_regex   None
barcodetag      CB
outdir  /path/barcodes/barcodes
sam     False
func    <function run_filterbarcodes at 0x2adffe7c13a0>
[E::hts_open_format] Failed to open file "/path/barcodes/ACTACGACACTTACAG-1_Q39PPG" : Remote I/O error
[E::hts_open_format] Failed to open file "/path/barcodes/ACTACGACACTTACAG-1_COX78C" : Remote I/O error
[E::hts_open_format] Failed to open file "/path/barcodes/CAAGCTAAGAGAGTTT-1_P1XYL0" : Remote I/O error

I get this error line for even more barcodes, those above are just the first three of the error message. The error proceeds with:

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/env/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/env/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/env/lib/python3.8/site-packages/sinto/filterbarcodes.py", line 33, in _iterate_reads
    bamlist = [pysam.AlignmentFile(x, filemode, header=newhead) for x in filelist]
  File "/env/lib/python3.8/site-packages/sinto/filterbarcodes.py", line 33, in <listcomp>
    bamlist = [pysam.AlignmentFile(x, filemode, header=newhead) for x in filelist]
  File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 915, in pysam.libcalignmentfile.AlignmentFile._open
OSError: [Errno 121] could not open alignment file `/path/barcodes/ACTACGACACTTACAG-1_Q39PPG`: Remote I/O error
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/env/bin/sinto", line 10, in <module>
    sys.exit(main())
  File "/env/lib/python3.8/site-packages/sinto/arguments.py", line 552, in main
    options.func(options)
  File "/env/lib/python3.8/site-packages/sinto/utils.py", line 24, in wrapper
    func(args)
  File "/env/lib/python3.8/site-packages/sinto/cli.py", line 18, in run_filterbarcodes
    filterbarcodes.filterbarcodes(
  File "/env/lib/python3.8/site-packages/sinto/filterbarcodes.py", line 114, in filterbarcodes
    idents = p.map_async(
  File "/env/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
OSError: [Errno 121] could not open alignment file `/path/barcodes/ACTACGACACTTACAG-1_Q39PPG`: Remote I/O error

**Comment by timoast** [comment]
Sorry for the late reply, I'm not sure but maybe this is due to the open file limit. You can increase the limit using `ulimit -a`
