### ISSUE TITLE
issue running filterbarcodes

### ISSUE THREAD

**Issue by tagaler** [timoast/sinto#7]
Thank you for making this tool, I was searching for something like this and couldn't get other things I found to work. It was difficult to find yours. Im trying to run sinto filterbarcodes to create pseudobulk data. I sam sorted and indexed my bam files and trying ran sinto filterbarcodes, and got the following error 

Traceback (most recent call last):
  File "/home/tasakis/anaconda2/envs/SingleCells/bin/sinto", line 216, in <module>
    options.func(options)
  File "/home/tasakis/anaconda2/envs/SingleCells/lib/python3.6/site-packages/sinto/utils.py", line 21, in wrapper
    func(args)
  File "/home/tasakis/anaconda2/envs/SingleCells/lib/python3.6/site-packages/sinto/cli.py", line 14, in run_filterbarcodes
    cellbarcode=options.barcodetag
  File "/home/tasakis/anaconda2/envs/SingleCells/lib/python3.6/site-packages/sinto/filterbarcodes.py", line 91, in filterbarcodes
    cb = utils.read_cell_barcode_file(cells)
  File "/home/tasakis/anaconda2/envs/SingleCells/lib/python3.6/site-packages/sinto/utils.py", line 198, in read_cell_barcode_file
    groups = line[1].split(",")
IndexError: list index out of range

Could you suggest what would lead to this error and how I might fix it?
Thank you for your help!

**Comment by timoast** [comment]
Can you provide part of the file you're using to specify the groups each cell belongs to?

**Comment by tagaler** [comment]
Thank you for your very quick response! A colleague found a mistake in the file I was using with the barcodes I fixed that and the problem was solved.

**Comment by Yansr3** [comment]
This may have been a long time, but I encountered the same issue. My issue was solved by using tsv format instead of csv for the cell barcodes list.
